name: Build Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Build
      run: chmod 777 gradlew
    - name: Build with Gradle
      id: build
      env:
        USE_ALPHAS: false
      run: ./gradlew setupGithubActions build
    - name: Create a Release
      id: create_release
      uses: meeDamian/github-release@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: betteranimalsplus-${{ steps.build.outputs.version }}
        draft: false
        prerelease: false
        files: build/libs/betteranimalsplus-${{ steps.build.outputs.version }}.jar
        gzip: false
    - name: Test CF upload
      uses: itsmeow/curseforge-upload@master
      with:
        token: ${{ secrets.CF_API_TOKEN }}
        project_id: 303557
        game_endpoint: minecraft
        file_path: build/libs/betteranimalsplus-${{ steps.build.outputs.version }}.jar
        changelog: Changelog not added yet...
        display_name: Better Animals Plus ${{ steps.build.outputs.version }}
        game_versions: minecraft-1-14:1.14.4,Java 8,Forge
        release_type: release
    - name: Build Success
      id: build-success
      uses: itsmeow/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        data: "{\"embeds\":[{\"title\":\"Release Build\",\"url\":\"https://github.com/itsmeow/betteranimalsplus/releases/tag/${{ steps.build.outputs.version }}\",\"description\":\"Tag: ${{ steps.build.outputs.version }}\\nStatus: Successful\",\"color\":65280,\"author\":{\"name\":\"${{ github.event.user.login }}\",\"url\":\"${{ github.event.user.html_url }}\",\"icon_url\":\"${{ github.event.user.avatar_url }}\"}}]}"
    - name: Build Fail
      id: build-fail
      if: failure()
      uses: itsmeow/webhook-action@master
      env:
        data: "{\"embeds\":[{\"title\":\"Release Build\",\"url\":\"https://github.com/itsmeow/betteranimalsplus/releases/tag/${{ steps.build.outputs.version }}\",\"description\":\"Tag: ${{ steps.build.outputs.version }}\\nStatus: Failed\",\"color\":16711680,\"author\":{\"name\":\"${{ github.event.user.login }}\",\"url\":\"${{ github.event.user.html_url }}\",\"icon_url\":\"${{ github.event.user.avatar_url }}\"}}]}"
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}\
