name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create a Release
      id: create_release
      uses: itsmeow/create-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: alpha-1.14.4-7.2.1.48
        release_name: betteranimalsplus-alpha-1.14.4-7.2.1.48
        draft: false
        prerelease: true
        commitish: ${{ github.sha }}