name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create a Release
      id: create_release
      uses: meeDamian/github-release@v1.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: alpha-1.14.4-7.2.1.48
        name: betteranimalsplus-alpha-1.14.4-7.2.1.48
        draft: false
        prerelease: true
        commitish: ${{ github.sha }}