name: Build Commit

on:
  pull_request:
    paths-ignore:
    - '*.md'
    - 'LICENSE'
    - '.github/**'
    - 'src/main/resources/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Build
      run: chmod 777 gradlew
    - name: Build with Gradle
      id: build
      run: ./gradlew build
    - name: Build Success
      id: build-success
      uses: itsmeow/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        data: {"embeds":[{"title":"Pull Request Build (#${{ github.event[0].number }})","url":"${{ github.event[0].url }}","description":"To Branch: ${{ github.event[0].base.ref }}\nStatus: Successful","color":65280,"author":{"name":"${{ github.event[0].user.login }}","url":"${{ github.event[0].user.html_url }}","icon_url":"${{ github.event[0].user.avatar_url }}"}}]}
    - name: Build Fail
      id: build-fail
      if: failure()
      uses: itsmeow/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        data: {"embeds":[{"title":"Pull Request Build (#${{ github.event[0].number }})","url":"${{ github.event[0].url }}","description":"To Branch: ${{ github.event[0].base.ref }}\nStatus: Failed","color":16711680,"author":{"name":"${{ github.event[0].user.login }}","url":"${{ github.event[0].user.html_url }}","icon_url":"${{ github.event[0].user.avatar_url }}"}}]}